const AUTH_PATHS = {
  BASE: '/auth',
  LOGIN: 'login',
  FORGOT_PASSWORD: 'forgot-password',
  REGISTER: 'register',
  VERIFY_EMAIL: 'verify-email',
  VERIFY_OTP: 'verify-otp',
};

const ADMIN_PATHS = {
  BASE: '/admin',
  DASHBOARD: 'dashboard',
  DETAIL: 'detail',
  RECIPE: 'recipe',
  USER: 'user',
  INGREDIENT: 'ingredient',
  CREATE: 'create',
};

const USER_PATHS = {
  BASE: '/',
  PROFILE: 'profile',
  RECIPE: 'recipe',
  CREATE: 'create',
  INGREDIENT: 'ingredient',
  AI_GENERATOR: 'ai-generator',
};

export const _ROUTER_NESTED_PATHS = {
  AUTH: {
    BASE: AUTH_PATHS.BASE,
    LOGIN: AUTH_PATHS.LOGIN,
    REGISTER: AUTH_PATHS.REGISTER,
    FORGOT_PASSWORD: AUTH_PATHS.FORGOT_PASSWORD,
    VERIFY_EMAIL: AUTH_PATHS.VERIFY_EMAIL,
    VERIFY_OTP: AUTH_PATHS.VERIFY_OTP,
  },
  ADMIN: {
    BASE: ADMIN_PATHS.BASE,
    DASHBOARD: ADMIN_PATHS.DASHBOARD,
    DETAIL: ADMIN_PATHS.DETAIL,
    RECIPE: ADMIN_PATHS.RECIPE,
    USER: ADMIN_PATHS.USER,
    INGREDIENT: ADMIN_PATHS.INGREDIENT,
    CREATE: ADMIN_PATHS.CREATE,
  },
  USER: {
    BASE: USER_PATHS.BASE,
    PROFILE: USER_PATHS.PROFILE,
    RECIPE: USER_PATHS.RECIPE,
    CREATE: USER_PATHS.CREATE,
    AI_GENERATOR: USER_PATHS.AI_GENERATOR,
    INGREDIENT: USER_PATHS.INGREDIENT,
  },
};

const createFullRoutes = () => {
  return {
    HOME: _ROUTER_NESTED_PATHS.USER.BASE,

    // User
    PROFILE: `${_ROUTER_NESTED_PATHS.USER.BASE}${_ROUTER_NESTED_PATHS.USER.PROFILE}`,
    RECIPE: `${_ROUTER_NESTED_PATHS.USER.BASE}${_ROUTER_NESTED_PATHS.USER.RECIPE}`,
    CREATE_RECIPE: `${_ROUTER_NESTED_PATHS.USER.BASE}${_ROUTER_NESTED_PATHS.USER.RECIPE}/${_ROUTER_NESTED_PATHS.USER.CREATE}`,
    INGREDIENT: `${_ROUTER_NESTED_PATHS.USER.BASE}${_ROUTER_NESTED_PATHS.USER.INGREDIENT}`,
    AI_GENERATOR: `${_ROUTER_NESTED_PATHS.USER.BASE}${_ROUTER_NESTED_PATHS.USER.AI_GENERATOR}`,

    // Admin
    ADMIN_DASHBOARD: `${_ROUTER_NESTED_PATHS.ADMIN.BASE}/${_ROUTER_NESTED_PATHS.ADMIN.DASHBOARD}`,
    ADMIN_DASHBOARD_RECIPE: `${_ROUTER_NESTED_PATHS.ADMIN.BASE}/${_ROUTER_NESTED_PATHS.ADMIN.DASHBOARD}/${_ROUTER_NESTED_PATHS.ADMIN.RECIPE}`,
    ADMIN_DASHBOARD_USER: `${_ROUTER_NESTED_PATHS.ADMIN.BASE}/${_ROUTER_NESTED_PATHS.ADMIN.DASHBOARD}/${_ROUTER_NESTED_PATHS.ADMIN.USER}`,
    ADMIN_DASHBOARD_INGREDIENT: `${_ROUTER_NESTED_PATHS.ADMIN.BASE}/${_ROUTER_NESTED_PATHS.ADMIN.DASHBOARD}/${_ROUTER_NESTED_PATHS.ADMIN.INGREDIENT}`,
    ADMIN_DASHBOARD_INGREDIENT_CREATE: `${_ROUTER_NESTED_PATHS.ADMIN.BASE}/${_ROUTER_NESTED_PATHS.ADMIN.DASHBOARD}/${_ROUTER_NESTED_PATHS.ADMIN.INGREDIENT}/${_ROUTER_NESTED_PATHS.ADMIN.CREATE}`,

    ADMIN_DETAIL: `${_ROUTER_NESTED_PATHS.ADMIN.BASE}/${_ROUTER_NESTED_PATHS.ADMIN.DETAIL}`,
    ADMIN_DETAIL_INGREDIENT: `${_ROUTER_NESTED_PATHS.ADMIN.BASE}/${_ROUTER_NESTED_PATHS.ADMIN.DETAIL}/${_ROUTER_NESTED_PATHS.ADMIN.INGREDIENT}`,

    // Auth
    LOGIN: `${_ROUTER_NESTED_PATHS.AUTH.BASE}/${_ROUTER_NESTED_PATHS.AUTH.LOGIN}`,
    REGISTER: `${_ROUTER_NESTED_PATHS.AUTH.BASE}/${_ROUTER_NESTED_PATHS.AUTH.REGISTER}`,
    FORGOT_PASSWORD: `${_ROUTER_NESTED_PATHS.AUTH.BASE}/${_ROUTER_NESTED_PATHS.AUTH.FORGOT_PASSWORD}`,
    VERIFY_EMAIL: `${_ROUTER_NESTED_PATHS.AUTH.BASE}/${_ROUTER_NESTED_PATHS.AUTH.VERIFY_EMAIL}`,
    VERIFY_OTP: `${_ROUTER_NESTED_PATHS.AUTH.BASE}/${_ROUTER_NESTED_PATHS.AUTH.VERIFY_OTP}`,
  };
};

export const _FULL_ROUTES = createFullRoutes();
