const AUTH_PATHS = {
  BASE: '/auth',
  LOGIN: 'login',
  FORGOT_PASSWORD: 'forgot-password',
  REGISTER: 'register',
  VERIFY_EMAIL: 'verify-email',
};

const ADMIN_PATHS = {
  BASE: '/admin',
  DASHBOARD: 'dashboard',
};

const USER_PATHS = {
  BASE: '/',
  RECIPES: 'recipes',
  AI_GENERATOR: 'ai-generator',
};

export const _ROUTER_NESTED_PATHS = {
  AUTH: {
    BASE: AUTH_PATHS.BASE,
    LOGIN: AUTH_PATHS.LOGIN,
    REGISTER: AUTH_PATHS.REGISTER,
    FORGOT_PASSWORD: AUTH_PATHS.FORGOT_PASSWORD,
    VERIFY_EMAIL: AUTH_PATHS.VERIFY_EMAIL,
  },
  ADMIN: {
    BASE: ADMIN_PATHS.BASE,
    DASHBOARD: ADMIN_PATHS.DASHBOARD,
  },
  USER: {
    BASE: USER_PATHS.BASE,
    RECIPES: USER_PATHS.RECIPES,
    AI_GENERATOR: USER_PATHS.AI_GENERATOR,
  },
};

const createFullRoutes = () => {
  return {
    HOME: _ROUTER_NESTED_PATHS.USER.BASE,
    RECIPES: `${_ROUTER_NESTED_PATHS.USER.BASE}${_ROUTER_NESTED_PATHS.USER.RECIPES}`,
    AI_GENERATOR: `${_ROUTER_NESTED_PATHS.USER.BASE}${_ROUTER_NESTED_PATHS.USER.AI_GENERATOR}`,

    // Auth
    LOGIN: `${_ROUTER_NESTED_PATHS.AUTH.BASE}/${_ROUTER_NESTED_PATHS.AUTH.LOGIN}`,
    REGISTER: `${_ROUTER_NESTED_PATHS.AUTH.BASE}/${_ROUTER_NESTED_PATHS.AUTH.REGISTER}`,
    FORGOT_PASSWORD: `${_ROUTER_NESTED_PATHS.AUTH.BASE}/${_ROUTER_NESTED_PATHS.AUTH.FORGOT_PASSWORD}`,
    VERIFY_EMAIL: `${_ROUTER_NESTED_PATHS.AUTH.BASE}/${_ROUTER_NESTED_PATHS.AUTH.VERIFY_EMAIL}`,
  };
};

export const _FULL_ROUTES = createFullRoutes();
