import { IRecipe } from '../types/recipe';

export const recipes: IRecipe[] = [
  {
    id: '1',
    title: 'Spicy Thai Basil Chicken',
    author: 'Chef Maria Rodriguez',
    authorId: 'chef-maria',
    status: 'published',
    difficulty: 'MEDIUM',
    upvotes: 234,
    rating: 4.8,
    cookTime: 25,
    flagged: false,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
    image: '/placeholder.svg?height=200&width=300',
    description: 'A flavorful Thai dish with aromatic basil and tender chicken',
    views: 1247,
    comments: 23,
    category: 'Asian',
  },
  {
    id: '2',
    title: 'Classic Margherita Pizza',
    author: 'Tony Romano',
    authorId: 'tony-romano',
    status: 'published',
    difficulty: 'EASY',
    upvotes: 456,
    rating: 4.9,
    cookTime: 45,
    flagged: false,
    createdAt: '2024-01-14',
    updatedAt: '2024-01-14',
    image: '/placeholder.svg?height=200&width=300',
    description: 'Traditional Italian pizza with fresh mozzarella and basil',
    views: 2156,
    comments: 45,
    category: 'Italian',
  },
  {
    id: '3',
    title: 'Suspicious Recipe Content',
    author: 'Bad Actor',
    authorId: 'bad-actor',
    status: 'draft',
    difficulty: 'EASY',
    upvotes: 2,
    rating: 2.1,
    cookTime: 15,
    flagged: true,
    createdAt: '2024-01-13',
    updatedAt: '2024-01-13',
    image: '/placeholder.svg?height=200&width=300',
    description: 'This recipe contains inappropriate content',
    views: 45,
    comments: 1,
    category: 'Other',
  },
  {
    id: '4',
    title: 'Beef Wellington Masterclass',
    author: 'Chef Gordon',
    authorId: 'chef-gordon',
    status: 'published',
    difficulty: 'HARD',
    upvotes: 189,
    rating: 4.7,
    cookTime: 120,
    flagged: false,
    createdAt: '2024-01-12',
    updatedAt: '2024-01-12',
    image: '/placeholder.svg?height=200&width=300',
    description: 'An advanced technique for the perfect beef wellington',
    views: 892,
    comments: 34,
    category: 'British',
  },
  {
    id: '5',
    title: 'Vegan Buddha Bowl',
    author: 'Sarah Chen',
    authorId: 'sarah-chen',
    status: 'published',
    difficulty: 'EASY',
    upvotes: 312,
    rating: 4.6,
    cookTime: 30,
    flagged: false,
    createdAt: '2024-01-11',
    updatedAt: '2024-01-11',
    image: '/placeholder.svg?height=200&width=300',
    description: 'Nutritious and colorful plant-based bowl',
    views: 1534,
    comments: 28,
    category: 'Vegan',
  },
];
