import { IUser } from '../types/user';

export const users: IUser[] = [
  {
    id: '1',
    name: 'Chef Maria Rodriguez',
    email: 'maria@example.com',
    avatar: '/placeholder.svg?height=60&width=60',
    role: 'chef',
    status: 'active',
    recipesCount: 24,
    followers: 1247,
    following: 89,
    joinedAt: '2023-06-15',
    lastActive: '2024-01-15',
    verified: true,
    totalUpvotes: 2341,
    location: 'Barcelona, Spain',
    bio: 'Professional chef specializing in Mediterranean cuisine',
  },
  {
    id: '2',
    name: 'Tony Romano',
    email: 'tony@example.com',
    avatar: '/placeholder.svg?height=60&width=60',
    role: 'user',
    status: 'active',
    recipesCount: 8,
    followers: 234,
    following: 156,
    joinedAt: '2023-08-22',
    lastActive: '2024-01-14',
    verified: false,
    totalUpvotes: 456,
    location: 'New York, USA',
    bio: 'Home cook passionate about Italian recipes',
  },
  {
    id: '3',
    name: 'Sarah Chen',
    email: 'sarah@example.com',
    avatar: '/placeholder.svg?height=60&width=60',
    role: 'moderator',
    status: 'active',
    recipesCount: 15,
    followers: 567,
    following: 234,
    joinedAt: '2023-05-10',
    lastActive: '2024-01-15',
    verified: true,
    totalUpvotes: 1234,
    location: 'San Francisco, USA',
    bio: 'Food blogger and community moderator',
  },
  {
    id: '4',
    name: 'Bad Actor',
    email: 'bad@example.com',
    avatar: '/placeholder.svg?height=60&width=60',
    role: 'user',
    status: 'suspended',
    recipesCount: 2,
    followers: 12,
    following: 5,
    joinedAt: '2024-01-01',
    lastActive: '2024-01-10',
    verified: false,
    totalUpvotes: 3,
    location: 'Unknown',
    bio: 'Suspended for policy violations',
  },
  {
    id: '5',
    name: 'Emma Wilson',
    email: 'emma@example.com',
    avatar: '/placeholder.svg?height=60&width=60',
    role: 'user',
    status: 'active',
    recipesCount: 12,
    followers: 345,
    following: 123,
    joinedAt: '2023-09-15',
    lastActive: '2024-01-13',
    verified: true,
    totalUpvotes: 678,
    location: 'London, UK',
    bio: 'Baking enthusiast and recipe developer',
  },
];
